// SLIP-44 registered coin types
// Source: https://github.com/satoshilabs/slips/blob/master/slip-0044.md
export const SLIP44_COINS: Record<string, { symbol: string; name: string }> = {
  "0": { symbol: "BTC", name: "Bitcoin" },
  "1": { symbol: "TEST", name: "Testnet" },
  "2": { symbol: "LTC", name: "Litecoin" },
  "3": { symbol: "DOGE", name: "Dogecoin" },
  "5": { symbol: "DASH", name: "Dash" },
  "20": { symbol: "DGB", name: "DigiByte" },
  "22": { symbol: "MONA", name: "Monacoin" },
  "42": { symbol: "DCR", name: "Decred" },
  "43": { symbol: "XEM", name: "NEM" },
  "60": { symbol: "ETH", name: "Ethereum" },
  "61": { symbol: "ETC", name: "Ethereum Classic" },
  "74": { symbol: "ICX", name: "ICON" },
  "118": { symbol: "ATOM", name: "Cosmos" },
  "128": { symbol: "XMR", name: "Monero" },
  "133": { symbol: "ZEC", name: "Zcash" },
  "134": { symbol: "LSK", name: "Lisk" },
  "135": { symbol: "STEEM", name: "Steem" },
  "136": { symbol: "FIRO", name: "Firo" },
  "137": { symbol: "KMD", name: "Komodo" },
  "141": { symbol: "XLM", name: "Stellar Lumens" },
  "144": { symbol: "XRP", name: "Ripple" },
  "145": { symbol: "BCH", name: "Bitcoin Cash" },
  "148": { symbol: "XLM", name: "Stellar" },
  "153": { symbol: "BTM", name: "Bytom" },
  "156": { symbol: "BTG", name: "Bitcoin Gold" },
  "171": { symbol: "HSR", name: "Hcash" },
  "175": { symbol: "RVN", name: "Ravencoin" },
  "178": { symbol: "POA", name: "POA Network" },
  "194": { symbol: "EOS", name: "EOS" },
  "195": { symbol: "TRX", name: "TRON" },
  "204": { symbol: "RDD", name: "Reddcoin" },
  "235": { symbol: "FIO", name: "FIO Protocol" },
  "236": { symbol: "BSV", name: "Bitcoin SV" },
  "242": { symbol: "NIM", name: "Nimiq" },
  "246": { symbol: "EWT", name: "Energy Web" },
  "283": { symbol: "ALGO", name: "Algorand" },
  "291": { symbol: "IOST", name: "IOST" },
  "301": { symbol: "HBAR", name: "Hedera" },
  "304": { symbol: "IOTA", name: "IOTA" },
  "308": { symbol: "VET", name: "VeChain" },
  "309": { symbol: "CCA", name: "Counos Coin" },
  "313": { symbol: "ZIL", name: "Zilliqa" },
  "330": { symbol: "LUNA", name: "Terra Classic" },
  "354": { symbol: "DOT", name: "Polkadot" },
  "360": { symbol: "ONE", name: "Harmony" },
  "397": { symbol: "NEAR", name: "NEAR Protocol" },
  "415": { symbol: "RSK", name: "RSK" },
  "425": { symbol: "AION", name: "Aion" },
  "434": { symbol: "KSM", name: "Kusama" },
  "457": { symbol: "AE", name: "Aeternity" },
  "459": { symbol: "KAVA", name: "Kava" },
  "461": { symbol: "FIL", name: "Filecoin" },
  "472": { symbol: "AR", name: "Arweave" },
  "474": { symbol: "CCX", name: "Counos X" },
  "478": { symbol: "CCA", name: "Counos Coin Avax" },
  "489": { symbol: "ETN", name: "Electroneum" },
  "494": { symbol: "RBTC", name: "RSK Mainnet" },
  "500": { symbol: "THETA", name: "Theta" },
  "501": { symbol: "SOL", name: "Solana" },
  "508": { symbol: "EGLD", name: "MultiversX" },
  "523": { symbol: "AXL", name: "Axelar" },
  "535": { symbol: "BCS", name: "Bitcoin Smart" },
  "539": { symbol: "FLOW", name: "Flow" },
  "540": { symbol: "THT", name: "Thought" },
  "568": { symbol: "LCC", name: "LitecoinCash" },
  "569": { symbol: "CKB", name: "Nervos" },
  "570": { symbol: "XDAI", name: "xDai" },
  "571": { symbol: "SRM", name: "Serum" },
  "573": { symbol: "VLX", name: "Velas" },
  "574": { symbol: "BPS", name: "BitcoinPoS" },
  "576": { symbol: "MATIC", name: "Polygon" },
  "592": { symbol: "CELO", name: "Celo" },
  "601": { symbol: "KLAY", name: "Klaytn" },
  "618": { symbol: "ADA", name: "Cardano" },
  "637": { symbol: "APT", name: "Aptos" },
  "659": { symbol: "ROSE", name: "Oasis Network" },
  "686": { symbol: "KAR", name: "Karura" },
  "693": { symbol: "VERSE", name: "Verse" },
  "700": { symbol: "USDT", name: "Tether" },
  "714": { symbol: "BNB", name: "BNB Chain" },
  "717": { symbol: "SDN", name: "Shiden" },
  "784": { symbol: "SUI", name: "Sui" },
  "787": { symbol: "ACA", name: "Acala" },
  "810": { symbol: "ASTR", name: "Astar" },
  "813": { symbol: "MINA", name: "Mina" },
  "818": { symbol: "VET", name: "VeChain" },
  "820": { symbol: "CLO", name: "Callisto" },
  "825": { symbol: "HNT", name: "Helium" },
  "858": { symbol: "SPC", name: "SpaceCoin" },
  "866": { symbol: "MAID", name: "MaidSafeCoin" },
  "877": { symbol: "QOOB", name: "Qoober" },
  "888": { symbol: "NEO", name: "NEO" },
  "889": { symbol: "TOMO", name: "TomoChain" },
  "904": { symbol: "HNS", name: "Handshake" },
  "906": { symbol: "SPL", name: "Solana SPL" },
  "907": { symbol: "STX", name: "Stacks" },
  "916": { symbol: "AURETH", name: "Aurora" },
  "919": { symbol: "XEC", name: "eCash" },
  "931": { symbol: "RUNE", name: "THORChain" },
  "966": { symbol: "MATIC", name: "Polygon" },
  "970": { symbol: "MEER", name: "Qitmeer" },
  "977": { symbol: "SCDO", name: "Scdo" },
  "989": { symbol: "ZBC", name: "Zcash on Bitcoin" },
  "990": { symbol: "BCHN", name: "Bitcoin Cash Node" },
  "991": { symbol: "KCC", name: "KuCoin Chain" },
  "992": { symbol: "BOBA", name: "Boba Network" },
  "994": { symbol: "EKTA", name: "Ekta" },
  "996": { symbol: "OKT", name: "OKX Chain" },
  "999": { symbol: "BCD", name: "Bitcoin Diamond" },
  "1000": { symbol: "BTN", name: "Bitcoin New" },
  "1001": { symbol: "TT", name: "ThunderCore" },
  "1007": { symbol: "FTM", name: "Fantom" },
  "1020": { symbol: "XCH", name: "Chia" },
  "1023": { symbol: "HT", name: "Huobi Token" },
  "1024": { symbol: "ONT", name: "Ontology" },
  "1030": { symbol: "CRO", name: "Cronos" },
  "1032": { symbol: "LBTC", name: "Lightning Bitcoin" },
  "1111": { symbol: "BBC", name: "BigBang Core" },
  "1145": { symbol: "LBC", name: "LBRY Credits" },
  "1155": { symbol: "UGAS", name: "Ultrain" },
  "1170": { symbol: "HOO", name: "Hoo Smart Chain" },
  "1234": { symbol: "STEP", name: "Step Network" },
  "1237": { symbol: "NOSTR", name: "Nostr" },
  "1284": { symbol: "GLMR", name: "Moonbeam" },
  "1285": { symbol: "MOVR", name: "Moonriver" },
  "1308": { symbol: "WAN", name: "Wanchain" },
  "1337": { symbol: "DFC", name: "DeFiChain" },
  "1397": { symbol: "HYN", name: "Hyperonchain" },
  "1410": { symbol: "XDC", name: "XinFin" },
  "1510": { symbol: "XSC", name: "Stakecoin" },
  "1512": { symbol: "AAC", name: "Double-A Chain" },
  "1517": { symbol: "ELS", name: "Elastos" },
  "1524": { symbol: "LKR", name: "Lkrcoin" },
  "1551": { symbol: "XRC", name: "Bitcoinrhodium" },
  "1552": { symbol: "XPI", name: "Piratechain" },
  "1616": { symbol: "ELV", name: "Eluvio" },
  "1618": { symbol: "ETHO", name: "Ether-1" },
  "1620": { symbol: "ATH", name: "Atheios" },
  "1642": { symbol: "NEW", name: "Newton" },
  "1654": { symbol: "BST", name: "BlockStamp" },
  "1657": { symbol: "BTA", name: "Btachain" },
  "1669": { symbol: "ARDR", name: "Ardor" },
  "1688": { symbol: "BCZ", name: "Bitcoinz" },
  "1729": { symbol: "XEC", name: "eCash" },
  "1776": { symbol: "LBTC", name: "Liquid BTC" },
  "1777": { symbol: "BBP", name: "Biblepay" },
  "1784": { symbol: "JPYS", name: "JPY Stablecoin" },
  "1789": { symbol: "EGEM", name: "Ethergem" },
  "1815": { symbol: "ADA", name: "Cardano" },
  "1856": { symbol: "TES", name: "Testcore" },
  "1888": { symbol: "ZTX", name: "Zetrix" },
  "1899": { symbol: "XEC", name: "eCash token" },
  "1907": { symbol: "BITCI", name: "Bitcichain" },
  "1919": { symbol: "VSC", name: "Vsystems" },
  "1926": { symbol: "CITY", name: "Citycoin" },
  "1955": { symbol: "UNT", name: "Unit" },
  "1977": { symbol: "SSP", name: "Smartshare" },
  "1984": { symbol: "GRLC", name: "Garlicoin" },
  "1985": { symbol: "PLSR", name: "Pulsar Coin" },
  "1987": { symbol: "EGEM", name: "Egem" },
  "1989": { symbol: "HODL", name: "Hodlcoin" },
  "1990": { symbol: "PHL", name: "Placeholders" },
  "1991": { symbol: "SC", name: "Sia" },
  "1996": { symbol: "MYB", name: "MyBit" },
  "1997": { symbol: "POLIS", name: "Polis" },
  "1998": { symbol: "BPA", name: "Bitcoin Pizza" },
  "1999": { symbol: "MONA", name: "Monacoin Testnet" },
  "2000": { symbol: "ALGO", name: "Algorand Testnet" },
  "2001": { symbol: "MLN", name: "Millenium" },
  "2002": { symbol: "MLN", name: "Millenero" },
  "2017": { symbol: "KIN", name: "Kin" },
  "2018": { symbol: "ZEN", name: "Horizen" },
  "2019": { symbol: "XSG", name: "SnowGem" },
  "2020": { symbol: "XZC", name: "Zcoin" },
  "2021": { symbol: "POLYX", name: "Polymesh" },
  "2022": { symbol: "ZRX", name: "0x" },
  "2046": { symbol: "ENJ", name: "Enjin Coin" },
  "2048": { symbol: "NULS", name: "Nuls" },
  "2049": { symbol: "XNS", name: "Insolar" },
  "2050": { symbol: "XTP", name: "Tap" },
  "2064": { symbol: "META", name: "Metadium" },
  "2074": { symbol: "VEO", name: "Amoveo" },
  "2077": { symbol: "SFRX", name: "EtherGem Sapphire" },
  "2083": { symbol: "MIT", name: "MIT" },
  "2086": { symbol: "KOTO", name: "Koto" },
  "2109": { symbol: "SBTC", name: "Super Bitcoin" },
  "2112": { symbol: "XDAI", name: "xDai" },
  "2125": { symbol: "GXC", name: "Gxchain" },
  "2136": { symbol: "FXTC", name: "FixedTradeCoin" },
  "2137": { symbol: "XIN", name: "Mixin" },
  "2140": { symbol: "BLOCK", name: "Blocknet" },
  "2147": { symbol: "IDX", name: "Idena" },
  "2152": { symbol: "CCC", name: "Counos Coin Classic" },
  "2153": { symbol: "CCL", name: "Counos Coin Lite" },
  "2160": { symbol: "CCE", name: "Counos Coin Enterprise" },
  "2169": { symbol: "PMEER", name: "Pmeer" },
  "2182": { symbol: "CHZ", name: "Chiliz" },
  "2199": { symbol: "SAMA", name: "Exosama" },
  "2200": { symbol: "EGG", name: "Nestree" },
  "2213": { symbol: "ETSC", name: "Ethereum Social" },
  "2217": { symbol: "FCTID", name: "Factom ID" },
  "2218": { symbol: "FCTAUTH", name: "Factom Auth" },
  "2221": { symbol: "ASK", name: "ASK" },
  "2222": { symbol: "CHC", name: "Chaincoin" },
  "2285": { symbol: "LAX", name: "LAPO" },
  "2301": { symbol: "QTUM", name: "Qtum" },
  "2302": { symbol: "RBTC", name: "RSK Testnet" },
  "2303": { symbol: "HNS", name: "Handshake" },
  "2304": { symbol: "OLT", name: "Oneledger" },
  "2305": { symbol: "XRD", name: "Radix" },
  "2338": { symbol: "TOP", name: "TOP Network" },
  "2365": { symbol: "XAZAB", name: "Xazab" },
  "2394": { symbol: "MNX", name: "MinexCoin" },
  "2458": { symbol: "COZX", name: "Cosmo Coin" },
  "2500": { symbol: "THETA", name: "Theta Testnet" },
  "2501": { symbol: "SOL", name: "Solana Testnet" },
  "2503": { symbol: "QCK", name: "Quicksilver" },
  "2504": { symbol: "ADA", name: "Cardano Testnet" },
  "2508": { symbol: "EGLD", name: "MultiversX Testnet" },
  "2570": { symbol: "PDEX", name: "Polkadex" },
  "2611": { symbol: "META", name: "Metaverse" },
  "2718": { symbol: "NAS", name: "Nebulas" },
  "2894": { symbol: "REOSC", name: "REOSCchain" },
  "2941": { symbol: "BND", name: "Blocknode" },
  "3003": { symbol: "LUX", name: "Luxcore" },
  "3030": { symbol: "HBAR", name: "Hedera HBAR" },
  "3053": { symbol: "DHT", name: "Dhat" },
  "3077": { symbol: "FO", name: "FIBOS" },
  "3104": { symbol: "XSN", name: "Stakenet" },
  "3125": { symbol: "CTC", name: "Creditcoin" },
  "3333": { symbol: "SXP", name: "Swipe" },
  "3377": { symbol: "RON", name: "Ronin" },
  "3381": { symbol: "DYN", name: "Dynamic" },
  "3383": { symbol: "SEQ", name: "Sequence" },
  "3552": { symbol: "DEO", name: "Destocoin" },
  "3564": { symbol: "DSM", name: "Desmos" },
  "3601": { symbol: "CKB", name: "Nervos CKB" },
  "3608": { symbol: "CCC", name: "Counos Coin Classic Testnet" },
  "4040": { symbol: "FC8", name: "FCH Network" },
  "4096": { symbol: "YDA", name: "YadaCoin" },
  "4218": { symbol: "IOTA", name: "IOTA" },
  "4219": { symbol: "SMR", name: "Shimmer" },
  "4242": { symbol: "AXE", name: "Axe" },
  "4343": { symbol: "XYM", name: "Symbol" },
  "4444": { symbol: "C4E", name: "Chain4Energy" },
  "4919": { symbol: "XVM", name: "Venidium" },
  "4999": { symbol: "BXN", name: "BlackFort" },
  "5006": { symbol: "SBC", name: "Senior Blockchain" },
  "5248": { symbol: "FIC", name: "FixonChain" },
  "5353": { symbol: "HNT", name: "Helium" },
  "5404": { symbol: "ISK", name: "ISKRA" },
  "5467": { symbol: "ALTME", name: "ALTME" },
  "5555": { symbol: "FUND", name: "Unification" },
  "5655": { symbol: "KLAY", name: "Klaytn Testnet" },
  "5656": { symbol: "QKC", name: "QuarkChain" },
  "5718": { symbol: "SEELE", name: "Seele" },
  "5729": { symbol: "HIVE", name: "Hive" },
  "5741": { symbol: "CHI", name: "Xaya" },
  "5757": { symbol: "STB", name: "STABILA" },
  "5895": { symbol: "VOW", name: "Vow" },
  "5920": { symbol: "SYS", name: "Syscoin" },
  "6060": { symbol: "GO", name: "GoChain" },
  "6599": { symbol: "RSC", name: "Royal Sports City" },
  "6666": { symbol: "GRIN", name: "Grin" },
  "6669": { symbol: "POLYX", name: "Polymesh Testnet" },
  "6686": { symbol: "MINA", name: "Mina Testnet" },
  "6688": { symbol: "ITZ", name: "Interzone" },
  "6779": { symbol: "CMPCO", name: "Compuco" },
  "6969": { symbol: "ZANO", name: "Zano" },
  "7000": { symbol: "NUKO", name: "Nekonium" },
  "7027": { symbol: "ELLA", name: "Ella" },
  "7028": { symbol: "AA", name: "AA" },
  "7030": { symbol: "NUM", name: "Numbers" },
  "7064": { symbol: "REOSC", name: "REOSC Ecosystem" },
  "7065": { symbol: "REOSCTEST", name: "REOSC Testnet" },
  "7070": { symbol: "PLANQ", name: "Planq" },
  "7077": { symbol: "BROCK", name: "Brock" },
  "7078": { symbol: "SIRIUS", name: "Sirius" },
  "7080": { symbol: "MCOIN", name: "MCoin" },
  "7083": { symbol: "QVT", name: "Qvolta" },
  "7091": { symbol: "TOPL", name: "Topl" },
  "7331": { symbol: "KLY", name: "Klyntar" },
  "7341": { symbol: "SHFT", name: "Shyft" },
  "7518": { symbol: "MEV", name: "MEVerse" },
  "7576": { symbol: "ADIL", name: "ADIL Chain" },
  "7777": { symbol: "BTV", name: "Bitvote" },
  "8000": { symbol: "SKY", name: "Skycoin" },
  "8080": { symbol: "DSRV", name: "DSRV" },
  "8181": { symbol: "BOC", name: "BeOne Chain" },
  "8192": { symbol: "PAC", name: "PAC Protocol" },
  "8217": { symbol: "KLAY", name: "Klaytn Cypress" },
  "8339": { symbol: "BTQ", name: "BitcoinQuark" },
  "8444": { symbol: "XCH", name: "Chia Testnet" },
  "8520": { symbol: "ATP", name: "Aleph" },
  "8680": { symbol: "PLMNT", name: "Planetarium" },
  "8866": { symbol: "UNKSO", name: "Funkaso" },
  "8886": { symbol: "BEET", name: "Beetle Coin" },
  "8888": { symbol: "SBTC", name: "Super Bitcoin" },
  "8964": { symbol: "NULS", name: "Nuls" },
  "8997": { symbol: "BBC", name: "Babacoin" },
  "8998": { symbol: "JGC", name: "JagoanCoin" },
  "8999": { symbol: "BTP", name: "Bitcoin Pay" },
  "9000": { symbol: "AVAX", name: "Avalanche" },
  "9001": { symbol: "EVMOS", name: "Evmos" },
  "9002": { symbol: "BERO", name: "Berachain" },
  "9003": { symbol: "BTW", name: "Bitcoin World" },
  "9004": { symbol: "TH", name: "TrueHKD" },
  "9005": { symbol: "AVAXTEST", name: "Avalanche Testnet" },
  "9006": { symbol: "BSC", name: "BNB Smart Chain" },
  "9797": { symbol: "NRG", name: "Energi" },
  "9888": { symbol: "BTF", name: "Bitcoin Faith" },
  "9999": { symbol: "GOD", name: "Bitcoin God" },
  "10000": { symbol: "FO", name: "FIBOS" },
  "10001": { symbol: "ATN", name: "Attention Network" },
  "10137": { symbol: "GFUN", name: "Gfun" },
  "10226": { symbol: "MMO", name: "Mammoth" },
  "10242": { symbol: "AOA", name: "Aurora" },
  "10291": { symbol: "NCASH", name: "Nucleus Vision" },
  "10507": { symbol: "NUM", name: "Numbers Mainnet" },
  "10605": { symbol: "XPI", name: "Lotus" },
  "11111": { symbol: "ESS", name: "Essentia" },
  "11115": { symbol: "STC", name: "Starcoin" },
  "12345": { symbol: "IPOS", name: "IPOS" },
  "12586": { symbol: "MINA", name: "Mina" },
  "13107": { symbol: "BTY", name: "BitYuan" },
  "13108": { symbol: "TFT", name: "ThreeFold" },
  "14001": { symbol: "WAX", name: "WAX" },
  "15845": { symbol: "BESC", name: "BESC" },
  "16181": { symbol: "XTZ", name: "Tezos" },
  "16754": { symbol: "ARDR", name: "Ardor Testnet" },
  "17001": { symbol: "XRF", name: "Refugecoin" },
  "18000": { symbol: "MTR", name: "Meter" },
  "19167": { symbol: "FLUX", name: "Flux" },
  "19169": { symbol: "RITO", name: "Ritocoin" },
  "19788": { symbol: "ML", name: "Mintlayer" },
  "20036": { symbol: "XND", name: "ndau" },
  "20809": { symbol: "CALL", name: "Callchain" },
  "21004": { symbol: "C4EI", name: "C4EI" },
  "21337": { symbol: "FXTC", name: "FixedTradeCoin" },
  "21888": { symbol: "PAC", name: "Pactus" },
  "22504": { symbol: "PWR", name: "PWRcoin" },
  "25252": { symbol: "BELL", name: "Bellcoin" },
  "25718": { symbol: "CHX", name: "Weown" },
  "29223": { symbol: "NEXA", name: "Nexa" },
  "30001": { symbol: "GGXT", name: "GGXT" },
  "31102": { symbol: "ESN", name: "EtherSocial Network" },
  "31337": { symbol: "PP", name: "PointPay" },
  "31397": { symbol: "WCH", name: "Wienchain" },
  "31415": { symbol: "XFAI", name: "XFAI" },
  "31618": { symbol: "MTG", name: "MultiGaming" },
  "32659": { symbol: "FUSE", name: "Fuse Token" },
  "33416": { symbol: "ZYN", name: "Wethio" },
  "33878": { symbol: "BTCZ", name: "BitcoinZ" },
  "34952": { symbol: "DUST", name: "Dust-Protocol" },
  "37992": { symbol: "FRTC", name: "Fastercoin" },
  "39321": { symbol: "AMA", name: "Amabig" },
  "42069": { symbol: "FART", name: "Fartcoin" },
  "43028": { symbol: "AXIV", name: "AXIV" },
  "43080": { symbol: "XLA", name: "Scala" },
  "47803": { symbol: "RES", name: "Resilio" },
  "48882": { symbol: "KETH", name: "Krypton World" },
  "49262": { symbol: "EVR", name: "Evrmore" },
  "49344": { symbol: "STASH", name: "STASH" },
  "52752": { symbol: "CELO", name: "Celo" },
  "53248": { symbol: "SEELEN", name: "Seelen" },
  "53588": { symbol: "BESC", name: "BESC Testnet" },
  "54321": { symbol: "GOKU", name: "Goku" },
  "61616": { symbol: "TKM", name: "ThankYouMoney" },
  "62621": { symbol: "MTNS", name: "OmotenashiCoin" },
  "65536": { symbol: "KYANITE", name: "Kyanite" },
  "69420": { symbol: "CORN", name: "Cornchain" },
  "73927": { symbol: "WEI", name: "Wei Chain" },
  "77777": { symbol: "ZT", name: "ZTrust" },
  "88888": { symbol: "RYO", name: "Ryo Currency" },
  "99999": { symbol: "WICC", name: "Waykichain" },
  "100100": { symbol: "ELF", name: "AELF" },
  "101010": { symbol: "SXC", name: "SexCoin" },
  "105105": { symbol: "STRAX", name: "Stratis" },
  "121337": { symbol: "CRP", name: "CranePay" },
  "131072": { symbol: "OBTC", name: "Optical Bitcoin" },
  "131337": { symbol: "SCRIBE", name: "Scribe" },
  "141341": { symbol: "HVH", name: "HavahCoin" },
  "161212": { symbol: "AMAX", name: "ArmorX" },
  "200101": { symbol: "MEWC", name: "MeowCoin" },
  "200625": { symbol: "AKA", name: "Akroma" },
  "200665": { symbol: "GENOM", name: "Genom" },
  "246529": { symbol: "ATS", name: "ArtisTS" },
  "246785": { symbol: "ART", name: "Artis" },
  "281123": { symbol: "KPL", name: "Kepler" },
  "333332": { symbol: "UOC", name: "UnitOfCoin" },
  "333333": { symbol: "SCSX", name: "SecureCryptoShares" },
  "424242": { symbol: "X42", name: "X42" },
  "534352": { symbol: "SCR", name: "Scroll" },
  "666666": { symbol: "VITE", name: "Vite" },
  "888888": { symbol: "SEA", name: "Second Exchange Alliance" },
  "999999": { symbol: "AMA", name: "AmazeChain" },
  "1048576": { symbol: "AIRDAO", name: "AirDAO" },
  "1111111": { symbol: "LOOP", name: "LoopNetwork" },
  "1234567": { symbol: "OWO", name: "OneWorld" },
  "1313114": { symbol: "ETHO", name: "Etho Protocol" },
  "1313161": { symbol: "ARTIS", name: "Artis" },
  "1313500": { symbol: "XERO", name: "Xerom" },
  "1712144": { symbol: "LAV", name: "LAVA" },
  "3924011": { symbol: "EPK", name: "EPIK Protocol" },
  "4741444": { symbol: "HYD", name: "Hydra" },
  "5249353": { symbol: "BCO", name: "BitcoinOre" },
  "5249354": { symbol: "KCN", name: "Kylacoin" },
  "5264398": { symbol: "NEBL", name: "Neblio" },
  "5655640": { symbol: "VGO", name: "VirtualGoodsOST" },
  "5718350": { symbol: "WGR", name: "Wagerr" },
  "5741564": { symbol: "NYX", name: "Nyx Coin" },
  "5741565": { symbol: "OWO", name: "OneWorldOST" },
  "6174414": { symbol: "ZIP", name: "Zippie" },
  "6382179": { symbol: "GRC", name: "Gridcoin" },
  "7562605": { symbol: "SOOM", name: "Soom" },
  "7567736": { symbol: "BCS", name: "Bitcoin Smart" },
  "7777777": { symbol: "BPA", name: "Bitcoin Pizza" },
  "7825266": { symbol: "WCN", name: "WorldCoin" },
  "7825267": { symbol: "LOOK", name: "LookCoin" },
  "8163271": { symbol: "QBC", name: "Quebecoin" },
  "8285266": { symbol: "GST", name: "GoldStarCoin" },
  "8388608": { symbol: "QTC", name: "Qitcoin" },
  "8523674": { symbol: "VEIL", name: "Veil" },
  "8964546": { symbol: "CHZ", name: "Chiliz Legacy Chain" },
  "9467634": { symbol: "SUPZ", name: "Suppocoin" },
  "10056085": { symbol: "TENT", name: "TENT" },
  "10242099": { symbol: "AMA", name: "AmazeChain" },
  "11259904": { symbol: "BELL", name: "Bellcoin" },
  "15426747": { symbol: "ZOD", name: "Zodiac" },
  "16777216": { symbol: "UM", name: "Penumbra" },
  "19910813": { symbol: "SKT", name: "Sukhavati" },
  "20180427": { symbol: "CLT", name: "CoinLoan Token" },
  "20201022": { symbol: "GENS", name: "GENS" },
  "20220430": { symbol: "VET", name: "VeChain Token" },
  "23159716": { symbol: "AHL", name: "Anhelion" },
  "28945486": { symbol: "MRN", name: "Moran Coin" },
  "29032022": { symbol: "FCON", name: "ForestCoin" },
  "29871983": { symbol: "BIT", name: "Bitcoin" },
  "37084815": { symbol: "HEX", name: "HEX" },
  "37310023": { symbol: "CLC", name: "ClockCoin" },
  "43523666": { symbol: "PEC", name: "Phoenix" },
  "61170086": { symbol: "NTN", name: "Neutrino" },
  "65100000": { symbol: "SWTH", name: "Switcheo" },
  "65100001": { symbol: "SWTH", name: "Switcheo Testnet" },
  "65100002": { symbol: "CSC", name: "Carbon" },
  "68378564": { symbol: "SBTC", name: "Super Bitcoin" },
  "69594230": { symbol: "BCR", name: "Bitcoinrh" },
  "88817293": { symbol: "NAM", name: "Namada" },
  "91772603": { symbol: "NUM", name: "Numeral" },
  "99999996": { symbol: "OKBT", name: "OKBToken" },
  "99999997": { symbol: "OKT", name: "OKT Chain" },
  "99999998": { symbol: "OKBT", name: "OKBToken Testnet" },
  "99999999": { symbol: "OKT", name: "OKT Chain Testnet" },
};

export function getSlip44Token(coinType: string): { symbol: string; name: string } | null {
  return SLIP44_COINS[coinType] || null;
}
